---

- name: "Ensure: {{ sshd_config_file_path }}"
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config_file_path }}"
    owner: "{{ sshd_config_file_owner }}"
    group: "{{ sshd_config_file_group }}"
    mode: "{{ sshd_config_file_mode }}"
  become: true
  notify: sshd restart
