---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: amazon_linux_2
    image: amazonlinux:2
    dockerfile: ../resources/Dockerfile.j2
    command: /usr/sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
  options:
    vv: true
    D: true
  links:
    hosts: ../resources/inventory/hosts
    group_vars: ../resources/inventory/group_vars/
    host_vars: ../resources/inventory/host_vars/
  playbooks:
    converge: ../resources/playbooks/converge.yml
verifier:
  name: testinfra
